/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const ClassInput = IDL.Record({
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'instructor' : IDL.Text,
  'dayOfWeek' : DayOfWeek,
  'room' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Attachment = IDL.Record({
  'blob' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const EventType = IDL.Variant({
  'workshop' : IDL.Null,
  'event' : IDL.Null,
  'competition' : IDL.Null,
  'activity' : IDL.Null,
});
export const EventInput = IDL.Record({
  'organiser' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'startAt' : Timestamp,
  'description' : IDL.Text,
  'endAt' : Timestamp,
  'registrationInfo' : IDL.Text,
  'attachments' : IDL.Vec(Attachment),
  'eventType' : EventType,
});
export const NoticeCategory = IDL.Variant({
  'fee' : IDL.Null,
  'exam' : IDL.Null,
  'academic' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const NoticeInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'pinned' : IDL.Bool,
  'category' : NoticeCategory,
  'attachments' : IDL.Vec(Attachment),
});
export const SyllabusTopic = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const SyllabusInput = IDL.Record({
  'subject' : IDL.Text,
  'topics' : IDL.Vec(SyllabusTopic),
  'materialLink' : IDL.Opt(IDL.Text),
  'attachments' : IDL.Vec(Attachment),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ItemId = IDL.Nat;
export const ClassSlot = IDL.Record({
  'id' : ItemId,
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'instructor' : IDL.Text,
  'dayOfWeek' : DayOfWeek,
  'room' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : ItemId,
  'organiser' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'startAt' : Timestamp,
  'description' : IDL.Text,
  'endAt' : Timestamp,
  'registrationInfo' : IDL.Text,
  'attachments' : IDL.Vec(Attachment),
  'eventType' : EventType,
});
export const FeedKind = IDL.Variant({
  'notice' : IDL.Null,
  'event' : IDL.Null,
  'competition' : IDL.Null,
});
export const FeedItem = IDL.Record({
  'at' : Timestamp,
  'id' : ItemId,
  'title' : IDL.Text,
  'preview' : IDL.Text,
  'kind' : FeedKind,
  'pinned' : IDL.Bool,
  'noticeCategory' : IDL.Opt(NoticeCategory),
  'eventType' : IDL.Opt(EventType),
});
export const Notice = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'pinned' : IDL.Bool,
  'category' : NoticeCategory,
  'attachments' : IDL.Vec(Attachment),
});
export const SyllabusEntry = IDL.Record({
  'id' : ItemId,
  'subject' : IDL.Text,
  'topics' : IDL.Vec(SyllabusTopic),
  'materialLink' : IDL.Opt(IDL.Text),
  'attachments' : IDL.Vec(Attachment),
});
export const SubjectDetail = IDL.Record({
  'subject' : IDL.Text,
  'classes' : IDL.Vec(ClassSlot),
  'syllabus' : IDL.Opt(SyllabusEntry),
});
export const SummaryCounts = IDL.Record({
  'upcomingEvents' : IDL.Nat,
  'newNotices' : IDL.Nat,
  'todaysClasses' : IDL.Nat,
});
export const EventTimeFilter = IDL.Variant({
  'all' : IDL.Null,
  'upcoming' : IDL.Null,
  'past' : IDL.Null,
});
export const EventFilter = IDL.Record({
  'time' : IDL.Opt(EventTimeFilter),
  'search' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Opt(EventType),
});
export const NoticeSort = IDL.Variant({
  'newest' : IDL.Null,
  'oldest' : IDL.Null,
});
export const NoticeFilter = IDL.Record({
  'sort' : IDL.Opt(NoticeSort),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(NoticeCategory),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([ClassInput], [IDL.Nat], []),
  'createEvent' : IDL.Func([EventInput], [IDL.Nat], []),
  'createNotice' : IDL.Func([NoticeInput], [IDL.Nat], []),
  'createSyllabus' : IDL.Func([SyllabusInput], [IDL.Nat], []),
  'deleteClass' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSyllabus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(ClassSlot)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getLatestFeed' : IDL.Func([IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
  'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'getSubjectDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SubjectDetail)],
      ['query'],
    ),
  'getSummaryCounts' : IDL.Func([], [SummaryCounts], ['query']),
  'getSyllabus' : IDL.Func([IDL.Nat], [IDL.Opt(SyllabusEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listClasses' : IDL.Func(
      [IDL.Opt(DayOfWeek)],
      [IDL.Vec(ClassSlot)],
      ['query'],
    ),
  'listEvents' : IDL.Func([EventFilter], [IDL.Vec(Event)], ['query']),
  'listNotices' : IDL.Func([NoticeFilter], [IDL.Vec(Notice)], ['query']),
  'listSyllabus' : IDL.Func([], [IDL.Vec(SyllabusEntry)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateClass' : IDL.Func([IDL.Nat, ClassInput], [IDL.Bool], []),
  'updateEvent' : IDL.Func([IDL.Nat, EventInput], [IDL.Bool], []),
  'updateNotice' : IDL.Func([IDL.Nat, NoticeInput], [IDL.Bool], []),
  'updateSyllabus' : IDL.Func([IDL.Nat, SyllabusInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const ClassInput = IDL.Record({
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'instructor' : IDL.Text,
    'dayOfWeek' : DayOfWeek,
    'room' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Attachment = IDL.Record({
    'blob' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const EventType = IDL.Variant({
    'workshop' : IDL.Null,
    'event' : IDL.Null,
    'competition' : IDL.Null,
    'activity' : IDL.Null,
  });
  const EventInput = IDL.Record({
    'organiser' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'startAt' : Timestamp,
    'description' : IDL.Text,
    'endAt' : Timestamp,
    'registrationInfo' : IDL.Text,
    'attachments' : IDL.Vec(Attachment),
    'eventType' : EventType,
  });
  const NoticeCategory = IDL.Variant({
    'fee' : IDL.Null,
    'exam' : IDL.Null,
    'academic' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const NoticeInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'pinned' : IDL.Bool,
    'category' : NoticeCategory,
    'attachments' : IDL.Vec(Attachment),
  });
  const SyllabusTopic = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const SyllabusInput = IDL.Record({
    'subject' : IDL.Text,
    'topics' : IDL.Vec(SyllabusTopic),
    'materialLink' : IDL.Opt(IDL.Text),
    'attachments' : IDL.Vec(Attachment),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ItemId = IDL.Nat;
  const ClassSlot = IDL.Record({
    'id' : ItemId,
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'instructor' : IDL.Text,
    'dayOfWeek' : DayOfWeek,
    'room' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : ItemId,
    'organiser' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'startAt' : Timestamp,
    'description' : IDL.Text,
    'endAt' : Timestamp,
    'registrationInfo' : IDL.Text,
    'attachments' : IDL.Vec(Attachment),
    'eventType' : EventType,
  });
  const FeedKind = IDL.Variant({
    'notice' : IDL.Null,
    'event' : IDL.Null,
    'competition' : IDL.Null,
  });
  const FeedItem = IDL.Record({
    'at' : Timestamp,
    'id' : ItemId,
    'title' : IDL.Text,
    'preview' : IDL.Text,
    'kind' : FeedKind,
    'pinned' : IDL.Bool,
    'noticeCategory' : IDL.Opt(NoticeCategory),
    'eventType' : IDL.Opt(EventType),
  });
  const Notice = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'pinned' : IDL.Bool,
    'category' : NoticeCategory,
    'attachments' : IDL.Vec(Attachment),
  });
  const SyllabusEntry = IDL.Record({
    'id' : ItemId,
    'subject' : IDL.Text,
    'topics' : IDL.Vec(SyllabusTopic),
    'materialLink' : IDL.Opt(IDL.Text),
    'attachments' : IDL.Vec(Attachment),
  });
  const SubjectDetail = IDL.Record({
    'subject' : IDL.Text,
    'classes' : IDL.Vec(ClassSlot),
    'syllabus' : IDL.Opt(SyllabusEntry),
  });
  const SummaryCounts = IDL.Record({
    'upcomingEvents' : IDL.Nat,
    'newNotices' : IDL.Nat,
    'todaysClasses' : IDL.Nat,
  });
  const EventTimeFilter = IDL.Variant({
    'all' : IDL.Null,
    'upcoming' : IDL.Null,
    'past' : IDL.Null,
  });
  const EventFilter = IDL.Record({
    'time' : IDL.Opt(EventTimeFilter),
    'search' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Opt(EventType),
  });
  const NoticeSort = IDL.Variant({ 'newest' : IDL.Null, 'oldest' : IDL.Null });
  const NoticeFilter = IDL.Record({
    'sort' : IDL.Opt(NoticeSort),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(NoticeCategory),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([ClassInput], [IDL.Nat], []),
    'createEvent' : IDL.Func([EventInput], [IDL.Nat], []),
    'createNotice' : IDL.Func([NoticeInput], [IDL.Nat], []),
    'createSyllabus' : IDL.Func([SyllabusInput], [IDL.Nat], []),
    'deleteClass' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSyllabus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Nat], [IDL.Opt(ClassSlot)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getLatestFeed' : IDL.Func([IDL.Nat], [IDL.Vec(FeedItem)], ['query']),
    'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'getSubjectDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SubjectDetail)],
        ['query'],
      ),
    'getSummaryCounts' : IDL.Func([], [SummaryCounts], ['query']),
    'getSyllabus' : IDL.Func([IDL.Nat], [IDL.Opt(SyllabusEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listClasses' : IDL.Func(
        [IDL.Opt(DayOfWeek)],
        [IDL.Vec(ClassSlot)],
        ['query'],
      ),
    'listEvents' : IDL.Func([EventFilter], [IDL.Vec(Event)], ['query']),
    'listNotices' : IDL.Func([NoticeFilter], [IDL.Vec(Notice)], ['query']),
    'listSyllabus' : IDL.Func([], [IDL.Vec(SyllabusEntry)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateClass' : IDL.Func([IDL.Nat, ClassInput], [IDL.Bool], []),
    'updateEvent' : IDL.Func([IDL.Nat, EventInput], [IDL.Bool], []),
    'updateNotice' : IDL.Func([IDL.Nat, NoticeInput], [IDL.Bool], []),
    'updateSyllabus' : IDL.Func([IDL.Nat, SyllabusInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };