/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'blob' : Uint8Array,
  'mimeType' : string,
  'filename' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ClassInput {
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'instructor' : string,
  'dayOfWeek' : DayOfWeek,
  'room' : string,
}
export interface ClassSlot {
  'id' : ItemId,
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'instructor' : string,
  'dayOfWeek' : DayOfWeek,
  'room' : string,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Event {
  'id' : ItemId,
  'organiser' : string,
  'title' : string,
  'venue' : string,
  'startAt' : Timestamp,
  'description' : string,
  'endAt' : Timestamp,
  'registrationInfo' : string,
  'attachments' : Array<Attachment>,
  'eventType' : EventType,
}
export interface EventFilter {
  'time' : [] | [EventTimeFilter],
  'search' : [] | [string],
  'eventType' : [] | [EventType],
}
export interface EventInput {
  'organiser' : string,
  'title' : string,
  'venue' : string,
  'startAt' : Timestamp,
  'description' : string,
  'endAt' : Timestamp,
  'registrationInfo' : string,
  'attachments' : Array<Attachment>,
  'eventType' : EventType,
}
export type EventTimeFilter = { 'all' : null } |
  { 'upcoming' : null } |
  { 'past' : null };
export type EventType = { 'workshop' : null } |
  { 'event' : null } |
  { 'competition' : null } |
  { 'activity' : null };
export interface FeedItem {
  'at' : Timestamp,
  'id' : ItemId,
  'title' : string,
  'preview' : string,
  'kind' : FeedKind,
  'pinned' : boolean,
  'noticeCategory' : [] | [NoticeCategory],
  'eventType' : [] | [EventType],
}
export type FeedKind = { 'notice' : null } |
  { 'event' : null } |
  { 'competition' : null };
export type ItemId = bigint;
export interface Notice {
  'id' : ItemId,
  'title' : string,
  'postedAt' : Timestamp,
  'body' : string,
  'author' : Principal,
  'pinned' : boolean,
  'category' : NoticeCategory,
  'attachments' : Array<Attachment>,
}
export type NoticeCategory = { 'fee' : null } |
  { 'exam' : null } |
  { 'academic' : null } |
  { 'urgent' : null } |
  { 'general' : null };
export interface NoticeFilter {
  'sort' : [] | [NoticeSort],
  'search' : [] | [string],
  'category' : [] | [NoticeCategory],
}
export interface NoticeInput {
  'title' : string,
  'body' : string,
  'pinned' : boolean,
  'category' : NoticeCategory,
  'attachments' : Array<Attachment>,
}
export type NoticeSort = { 'newest' : null } |
  { 'oldest' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SubjectDetail {
  'subject' : string,
  'classes' : Array<ClassSlot>,
  'syllabus' : [] | [SyllabusEntry],
}
export interface SummaryCounts {
  'upcomingEvents' : bigint,
  'newNotices' : bigint,
  'todaysClasses' : bigint,
}
export interface SyllabusEntry {
  'id' : ItemId,
  'subject' : string,
  'topics' : Array<SyllabusTopic>,
  'materialLink' : [] | [string],
  'attachments' : Array<Attachment>,
}
export interface SyllabusInput {
  'subject' : string,
  'topics' : Array<SyllabusTopic>,
  'materialLink' : [] | [string],
  'attachments' : Array<Attachment>,
}
export interface SyllabusTopic { 'title' : string, 'description' : string }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: create a class slot. Returns the new id.
   */
  'createClass' : ActorMethod<[ClassInput], bigint>,
  /**
   * / Admin-only: create an event or competition. Returns the new event id.
   */
  'createEvent' : ActorMethod<[EventInput], bigint>,
  /**
   * / Admin-only: create a notice. Returns the new notice id.
   */
  'createNotice' : ActorMethod<[NoticeInput], bigint>,
  /**
   * / Admin-only: create a syllabus entry. Returns the new id.
   */
  'createSyllabus' : ActorMethod<[SyllabusInput], bigint>,
  /**
   * / Admin-only: delete a class slot. Returns false when the id is unknown.
   */
  'deleteClass' : ActorMethod<[bigint], boolean>,
  /**
   * / Admin-only: delete an event. Returns false when the id is unknown.
   */
  'deleteEvent' : ActorMethod<[bigint], boolean>,
  /**
   * / Admin-only: delete a notice. Returns false when the id is unknown.
   */
  'deleteNotice' : ActorMethod<[bigint], boolean>,
  /**
   * / Admin-only: delete a syllabus entry. Returns false when the id is unknown.
   */
  'deleteSyllabus' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single class slot by id; null when it does not exist.
   */
  'getClass' : ActorMethod<[bigint], [] | [ClassSlot]>,
  /**
   * / Fetch a single event by id; null when it does not exist.
   */
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  /**
   * / Unified "Latest Updates" feed: pinned notices first, then recent notices,
   * / events, and competitions newest first, capped at `limit`.
   */
  'getLatestFeed' : ActorMethod<[bigint], Array<FeedItem>>,
  /**
   * / Fetch a single notice by id; null when it does not exist.
   */
  'getNotice' : ActorMethod<[bigint], [] | [Notice]>,
  /**
   * / Subject detail: syllabus outline plus associated class schedule.
   */
  'getSubjectDetail' : ActorMethod<[string], [] | [SubjectDetail]>,
  /**
   * / Quick-glance dashboard counts: upcoming events, new notices, today's classes.
   */
  'getSummaryCounts' : ActorMethod<[], SummaryCounts>,
  /**
   * / Fetch a syllabus entry by id; null when it does not exist.
   */
  'getSyllabus' : ActorMethod<[bigint], [] | [SyllabusEntry]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List class slots, optionally restricted to a single day of the week.
   */
  'listClasses' : ActorMethod<[[] | [DayOfWeek]], Array<ClassSlot>>,
  /**
   * / List events with optional type filter, upcoming/past filter, and keyword search.
   */
  'listEvents' : ActorMethod<[EventFilter], Array<Event>>,
  /**
   * / List notices with optional category filter, keyword search, and sort order.
   */
  'listNotices' : ActorMethod<[NoticeFilter], Array<Notice>>,
  /**
   * / List all syllabus entries.
   */
  'listSyllabus' : ActorMethod<[], Array<SyllabusEntry>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Admin-only: update an existing class slot. Returns false when the id is unknown.
   */
  'updateClass' : ActorMethod<[bigint, ClassInput], boolean>,
  /**
   * / Admin-only: update an existing event. Returns false when the id is unknown.
   */
  'updateEvent' : ActorMethod<[bigint, EventInput], boolean>,
  /**
   * / Admin-only: update an existing notice. Returns false when the id is unknown.
   */
  'updateNotice' : ActorMethod<[bigint, NoticeInput], boolean>,
  /**
   * / Admin-only: update an existing syllabus entry. Returns false when the id is unknown.
   */
  'updateSyllabus' : ActorMethod<[bigint, SyllabusInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];