/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Attachment {
    blob: Uint8Array;
    mimeType: string;
    filename: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ClassInput {
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: DayOfWeek;
    room: string;
}
export interface ClassSlot {
    id: ItemId;
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: DayOfWeek;
    room: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Event {
    id: ItemId;
    organiser: string;
    title: string;
    venue: string;
    startAt: Timestamp;
    description: string;
    endAt: Timestamp;
    registrationInfo: string;
    attachments: Array<Attachment>;
    eventType: EventType;
}
export interface EventFilter {
    time?: EventTimeFilter;
    search?: string;
    eventType?: EventType;
}
export interface EventInput {
    organiser: string;
    title: string;
    venue: string;
    startAt: Timestamp;
    description: string;
    endAt: Timestamp;
    registrationInfo: string;
    attachments: Array<Attachment>;
    eventType: EventType;
}
export interface FeedItem {
    at: Timestamp;
    id: ItemId;
    title: string;
    preview: string;
    kind: FeedKind;
    pinned: boolean;
    noticeCategory?: NoticeCategory;
    eventType?: EventType;
}
export type ItemId = bigint;
export interface Notice {
    id: ItemId;
    title: string;
    postedAt: Timestamp;
    body: string;
    author: Principal;
    pinned: boolean;
    category: NoticeCategory;
    attachments: Array<Attachment>;
}
export interface NoticeFilter {
    sort?: NoticeSort;
    search?: string;
    category?: NoticeCategory;
}
export interface NoticeInput {
    title: string;
    body: string;
    pinned: boolean;
    category: NoticeCategory;
    attachments: Array<Attachment>;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SubjectDetail {
    subject: string;
    classes: Array<ClassSlot>;
    syllabus?: SyllabusEntry;
}
export interface SummaryCounts {
    upcomingEvents: bigint;
    newNotices: bigint;
    todaysClasses: bigint;
}
export interface SyllabusEntry {
    id: ItemId;
    subject: string;
    topics: Array<SyllabusTopic>;
    materialLink?: string;
    attachments: Array<Attachment>;
}
export interface SyllabusInput {
    subject: string;
    topics: Array<SyllabusTopic>;
    materialLink?: string;
    attachments: Array<Attachment>;
}
export interface SyllabusTopic {
    title: string;
    description: string;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum EventTimeFilter {
    all = "all",
    upcoming = "upcoming",
    past = "past"
}
export enum EventType {
    workshop = "workshop",
    event = "event",
    competition = "competition",
    activity = "activity"
}
export enum FeedKind {
    notice = "notice",
    event = "event",
    competition = "competition"
}
export enum NoticeCategory {
    fee = "fee",
    exam = "exam",
    academic = "academic",
    urgent = "urgent",
    general = "general"
}
export enum NoticeSort {
    newest = "newest",
    oldest = "oldest"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Admin-only: create a class slot. Returns the new id.
     */
    createClass(input: ClassInput): Promise<bigint>;
    /**
     * / Admin-only: create an event or competition. Returns the new event id.
     */
    createEvent(input: EventInput): Promise<bigint>;
    /**
     * / Admin-only: create a notice. Returns the new notice id.
     */
    createNotice(input: NoticeInput): Promise<bigint>;
    /**
     * / Admin-only: create a syllabus entry. Returns the new id.
     */
    createSyllabus(input: SyllabusInput): Promise<bigint>;
    /**
     * / Admin-only: delete a class slot. Returns false when the id is unknown.
     */
    deleteClass(id: bigint): Promise<boolean>;
    /**
     * / Admin-only: delete an event. Returns false when the id is unknown.
     */
    deleteEvent(id: bigint): Promise<boolean>;
    /**
     * / Admin-only: delete a notice. Returns false when the id is unknown.
     */
    deleteNotice(id: bigint): Promise<boolean>;
    /**
     * / Admin-only: delete a syllabus entry. Returns false when the id is unknown.
     */
    deleteSyllabus(id: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Returns the backend API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a single class slot by id; null when it does not exist.
     */
    getClass(id: bigint): Promise<ClassSlot | null>;
    /**
     * / Fetch a single event by id; null when it does not exist.
     */
    getEvent(id: bigint): Promise<Event | null>;
    /**
     * / Unified "Latest Updates" feed: pinned notices first, then recent notices,
     * / events, and competitions newest first, capped at `limit`.
     */
    getLatestFeed(limit: bigint): Promise<Array<FeedItem>>;
    /**
     * / Fetch a single notice by id; null when it does not exist.
     */
    getNotice(id: bigint): Promise<Notice | null>;
    /**
     * / Subject detail: syllabus outline plus associated class schedule.
     */
    getSubjectDetail(subject: string): Promise<SubjectDetail | null>;
    /**
     * / Quick-glance dashboard counts: upcoming events, new notices, today's classes.
     */
    getSummaryCounts(): Promise<SummaryCounts>;
    /**
     * / Fetch a syllabus entry by id; null when it does not exist.
     */
    getSyllabus(id: bigint): Promise<SyllabusEntry | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List class slots, optionally restricted to a single day of the week.
     */
    listClasses(day: DayOfWeek | null): Promise<Array<ClassSlot>>;
    /**
     * / List events with optional type filter, upcoming/past filter, and keyword search.
     */
    listEvents(filter: EventFilter): Promise<Array<Event>>;
    /**
     * / List notices with optional category filter, keyword search, and sort order.
     */
    listNotices(filter: NoticeFilter): Promise<Array<Notice>>;
    /**
     * / List all syllabus entries.
     */
    listSyllabus(): Promise<Array<SyllabusEntry>>;
    schema(): Promise<string>;
    /**
     * / Admin-only: update an existing class slot. Returns false when the id is unknown.
     */
    updateClass(id: bigint, input: ClassInput): Promise<boolean>;
    /**
     * / Admin-only: update an existing event. Returns false when the id is unknown.
     */
    updateEvent(id: bigint, input: EventInput): Promise<boolean>;
    /**
     * / Admin-only: update an existing notice. Returns false when the id is unknown.
     */
    updateNotice(id: bigint, input: NoticeInput): Promise<boolean>;
    /**
     * / Admin-only: update an existing syllabus entry. Returns false when the id is unknown.
     */
    updateSyllabus(id: bigint, input: SyllabusInput): Promise<boolean>;
}
import type { Attachment as _Attachment, Cell as _Cell, ClassInput as _ClassInput, ClassSlot as _ClassSlot, DayOfWeek as _DayOfWeek, Error as _Error, Event as _Event, EventFilter as _EventFilter, EventInput as _EventInput, EventTimeFilter as _EventTimeFilter, EventType as _EventType, FeedItem as _FeedItem, FeedKind as _FeedKind, ItemId as _ItemId, Notice as _Notice, NoticeCategory as _NoticeCategory, NoticeFilter as _NoticeFilter, NoticeInput as _NoticeInput, NoticeSort as _NoticeSort, Result as _Result, Result__1 as _Result__1, SubjectDetail as _SubjectDetail, SyllabusEntry as _SyllabusEntry, SyllabusInput as _SyllabusInput, SyllabusTopic as _SyllabusTopic, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClass(arg0: ClassInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: EventInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_EventInput_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_EventInput_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotice(arg0: NoticeInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(to_candid_NoticeInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(to_candid_NoticeInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSyllabus(arg0: SyllabusInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSyllabus(to_candid_SyllabusInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSyllabus(to_candid_SyllabusInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClass(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteSyllabus(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSyllabus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSyllabus(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: bigint): Promise<ClassSlot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestFeed(arg0: bigint): Promise<Array<FeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestFeed(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestFeed(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: bigint): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectDetail(arg0: string): Promise<SubjectDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectDetail(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectDetail(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummaryCounts(): Promise<SummaryCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryCounts();
            return result;
        }
    }
    async getSyllabus(arg0: bigint): Promise<SyllabusEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSyllabus(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSyllabus(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listClasses(arg0: DayOfWeek | null): Promise<Array<ClassSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClasses(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClasses(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(arg0: EventFilter): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents(to_candid_EventFilter_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents(to_candid_EventFilter_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotices(arg0: NoticeFilter): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices(to_candid_NoticeFilter_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices(to_candid_NoticeFilter_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSyllabus(): Promise<Array<SyllabusEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSyllabus();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSyllabus();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateClass(arg0: bigint, arg1: ClassInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, to_candid_ClassInput_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: EventInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_EventInput_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_EventInput_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNotice(arg0: bigint, arg1: NoticeInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0, to_candid_NoticeInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0, to_candid_NoticeInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSyllabus(arg0: bigint, arg1: SyllabusInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSyllabus(arg0, to_candid_SyllabusInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSyllabus(arg0, to_candid_SyllabusInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Cell_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ClassSlot_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassSlot): ClassSlot {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return "workshop" in value ? EventType.workshop : "event" in value ? EventType.event : "competition" in value ? EventType.competition : "activity" in value ? EventType.activity : value;
}
function from_candid_Event_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_FeedItem_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedItem): FeedItem {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_FeedKind_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedKind): FeedKind {
    return "notice" in value ? FeedKind.notice : "event" in value ? FeedKind.event : "competition" in value ? FeedKind.competition : value;
}
function from_candid_NoticeCategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeCategory): NoticeCategory {
    return "fee" in value ? NoticeCategory.fee : "exam" in value ? NoticeCategory.exam : "academic" in value ? NoticeCategory.academic : "urgent" in value ? NoticeCategory.urgent : "general" in value ? NoticeCategory.general : value;
}
function from_candid_Notice_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectDetail_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectDetail): SubjectDetail {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SyllabusEntry_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SyllabusEntry): SyllabusEntry {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassSlot]): ClassSlot | null {
    return value.length === 0 ? null : from_candid_ClassSlot_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NoticeCategory]): NoticeCategory | null {
    return value.length === 0 ? null : from_candid_NoticeCategory_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EventType]): EventType | null {
    return value.length === 0 ? null : from_candid_EventType_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : from_candid_Notice_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubjectDetail]): SubjectDetail | null {
    return value.length === 0 ? null : from_candid_SubjectDetail_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SyllabusEntry]): SyllabusEntry | null {
    return value.length === 0 ? null : from_candid_SyllabusEntry_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n19(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n23(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: _DayOfWeek;
    room: string;
}): {
    id: ItemId;
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: DayOfWeek;
    room: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        subject: value.subject,
        endTime: value.endTime,
        instructor: value.instructor,
        dayOfWeek: from_candid_DayOfWeek_n29(_uploadFile, _downloadFile, value.dayOfWeek),
        room: value.room
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    organiser: string;
    title: string;
    venue: string;
    startAt: _Timestamp;
    description: string;
    endAt: _Timestamp;
    registrationInfo: string;
    attachments: Array<_Attachment>;
    eventType: _EventType;
}): {
    id: ItemId;
    organiser: string;
    title: string;
    venue: string;
    startAt: Timestamp;
    description: string;
    endAt: Timestamp;
    registrationInfo: string;
    attachments: Array<Attachment>;
    eventType: EventType;
} {
    return {
        id: value.id,
        organiser: value.organiser,
        title: value.title,
        venue: value.venue,
        startAt: value.startAt,
        description: value.description,
        endAt: value.endAt,
        registrationInfo: value.registrationInfo,
        attachments: value.attachments,
        eventType: from_candid_EventType_n33(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    at: _Timestamp;
    id: _ItemId;
    title: string;
    preview: string;
    kind: _FeedKind;
    pinned: boolean;
    noticeCategory: [] | [_NoticeCategory];
    eventType: [] | [_EventType];
}): {
    at: Timestamp;
    id: ItemId;
    title: string;
    preview: string;
    kind: FeedKind;
    pinned: boolean;
    noticeCategory?: NoticeCategory;
    eventType?: EventType;
} {
    return {
        at: value.at,
        id: value.id,
        title: value.title,
        preview: value.preview,
        kind: from_candid_FeedKind_n37(_uploadFile, _downloadFile, value.kind),
        pinned: value.pinned,
        noticeCategory: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.noticeCategory)),
        eventType: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.eventType))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    title: string;
    postedAt: _Timestamp;
    body: string;
    author: Principal;
    pinned: boolean;
    category: _NoticeCategory;
    attachments: Array<_Attachment>;
}): {
    id: ItemId;
    title: string;
    postedAt: Timestamp;
    body: string;
    author: Principal;
    pinned: boolean;
    category: NoticeCategory;
    attachments: Array<Attachment>;
} {
    return {
        id: value.id,
        title: value.title,
        postedAt: value.postedAt,
        body: value.body,
        author: value.author,
        pinned: value.pinned,
        category: from_candid_NoticeCategory_n39(_uploadFile, _downloadFile, value.category),
        attachments: value.attachments
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    classes: Array<_ClassSlot>;
    syllabus: [] | [_SyllabusEntry];
}): {
    subject: string;
    classes: Array<ClassSlot>;
    syllabus?: SyllabusEntry;
} {
    return {
        subject: value.subject,
        classes: from_candid_vec_n47(_uploadFile, _downloadFile, value.classes),
        syllabus: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.syllabus))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    subject: string;
    topics: Array<_SyllabusTopic>;
    materialLink: [] | [string];
    attachments: Array<_Attachment>;
}): {
    id: ItemId;
    subject: string;
    topics: Array<SyllabusTopic>;
    materialLink?: string;
    attachments: Array<Attachment>;
} {
    return {
        id: value.id,
        subject: value.subject,
        topics: value.topics,
        materialLink: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.materialLink)),
        attachments: value.attachments
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedItem>): Array<FeedItem> {
    return value.map((x)=>from_candid_FeedItem_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassSlot>): Array<ClassSlot> {
    return value.map((x)=>from_candid_ClassSlot_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SyllabusEntry>): Array<SyllabusEntry> {
    return value.map((x)=>from_candid_SyllabusEntry_n49(_uploadFile, _downloadFile, x));
}
function to_candid_ClassInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassInput): _ClassInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DayOfWeek_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_EventFilter_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter): _EventFilter {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_EventInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventInput): _EventInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_EventTimeFilter_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventTimeFilter): _EventTimeFilter {
    return value == EventTimeFilter.all ? {
        all: null
    } : value == EventTimeFilter.upcoming ? {
        upcoming: null
    } : value == EventTimeFilter.past ? {
        past: null
    } : value;
}
function to_candid_EventType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return value == EventType.workshop ? {
        workshop: null
    } : value == EventType.event ? {
        event: null
    } : value == EventType.competition ? {
        competition: null
    } : value == EventType.activity ? {
        activity: null
    } : value;
}
function to_candid_NoticeCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeCategory): _NoticeCategory {
    return value == NoticeCategory.fee ? {
        fee: null
    } : value == NoticeCategory.exam ? {
        exam: null
    } : value == NoticeCategory.academic ? {
        academic: null
    } : value == NoticeCategory.urgent ? {
        urgent: null
    } : value == NoticeCategory.general ? {
        general: null
    } : value;
}
function to_candid_NoticeFilter_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeFilter): _NoticeFilter {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_NoticeInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeInput): _NoticeInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_NoticeSort_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoticeSort): _NoticeSort {
    return value == NoticeSort.newest ? {
        newest: null
    } : value == NoticeSort.oldest ? {
        oldest: null
    } : value;
}
function to_candid_SyllabusInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SyllabusInput): _SyllabusInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek | null): [] | [_DayOfWeek] {
    return value === null ? candid_none() : candid_some(to_candid_DayOfWeek_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organiser: string;
    title: string;
    venue: string;
    startAt: Timestamp;
    description: string;
    endAt: Timestamp;
    registrationInfo: string;
    attachments: Array<Attachment>;
    eventType: EventType;
}): {
    organiser: string;
    title: string;
    venue: string;
    startAt: _Timestamp;
    description: string;
    endAt: _Timestamp;
    registrationInfo: string;
    attachments: Array<_Attachment>;
    eventType: _EventType;
} {
    return {
        organiser: value.organiser,
        title: value.title,
        venue: value.venue,
        startAt: value.startAt,
        description: value.description,
        endAt: value.endAt,
        registrationInfo: value.registrationInfo,
        attachments: value.attachments,
        eventType: to_candid_EventType_n11(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: string;
    pinned: boolean;
    category: NoticeCategory;
    attachments: Array<Attachment>;
}): {
    title: string;
    body: string;
    pinned: boolean;
    category: _NoticeCategory;
    attachments: Array<_Attachment>;
} {
    return {
        title: value.title,
        body: value.body,
        pinned: value.pinned,
        category: to_candid_NoticeCategory_n14(_uploadFile, _downloadFile, value.category),
        attachments: value.attachments
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    topics: Array<SyllabusTopic>;
    materialLink?: string;
    attachments: Array<Attachment>;
}): {
    subject: string;
    topics: Array<_SyllabusTopic>;
    materialLink: [] | [string];
    attachments: Array<_Attachment>;
} {
    return {
        subject: value.subject,
        topics: value.topics,
        materialLink: value.materialLink ? candid_some(value.materialLink) : candid_none(),
        attachments: value.attachments
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    time?: EventTimeFilter;
    search?: string;
    eventType?: EventType;
}): {
    time: [] | [_EventTimeFilter];
    search: [] | [string];
    eventType: [] | [_EventType];
} {
    return {
        time: value.time ? candid_some(to_candid_EventTimeFilter_n55(_uploadFile, _downloadFile, value.time)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        eventType: value.eventType ? candid_some(to_candid_EventType_n11(_uploadFile, _downloadFile, value.eventType)) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sort?: NoticeSort;
    search?: string;
    category?: NoticeCategory;
}): {
    sort: [] | [_NoticeSort];
    search: [] | [string];
    category: [] | [_NoticeCategory];
} {
    return {
        sort: value.sort ? candid_some(to_candid_NoticeSort_n59(_uploadFile, _downloadFile, value.sort)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        category: value.category ? candid_some(to_candid_NoticeCategory_n14(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: DayOfWeek;
    room: string;
}): {
    startTime: string;
    subject: string;
    endTime: string;
    instructor: string;
    dayOfWeek: _DayOfWeek;
    room: string;
} {
    return {
        startTime: value.startTime,
        subject: value.subject,
        endTime: value.endTime,
        instructor: value.instructor,
        dayOfWeek: to_candid_DayOfWeek_n8(_uploadFile, _downloadFile, value.dayOfWeek),
        room: value.room
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
